### ISSUE TITLE
Problema ao adicionar arquivos ao model

### ISSUE THREAD

**Issue by GermainGirndt** [maratonadev-br/desafio-1-2020#10]
**Sistema Operacional:** Ubuntu 20.04 LTS
**Navegador:** Google Chrome 84.0.4147.105

**Problema:** 

Após subir com sucesso os arquivos .zip contendo as imagens .png e .jpg na plataforma de Visual Recognition, eis que quando eu seleciono os arquivos os zip files e clico para adicionar no model, a plataforma exibe normalmente o status de carregamento ''Loading file into model'. 

Entretanto, **essa tela continua indefinidamente por mais de uma hora**, muito embora eu esteja tentando subir um total de menos de 70 imagens, distribuídas em 4 zips separadas.

**Seção com "Loading"**
![image](https://user-images.githubusercontent.com/52306002/90338909-58d21080-dfc3-11ea-9487-a0fd42a27a32.png)

**Tela da Plataforma**
![image](https://user-images.githubusercontent.com/52306002/90338642-700ffe80-dfc1-11ea-8f25-b500ceb10ec6.png)

--------

**Tentativas de Solucionar o Problema já empreendidas:**

- Recarregar a página (F5 / ctrl + F5). A página recarrega e se apresenta como se eu nunca tivesse ordenado que as zips fossem adicionadas ao model.
![image](https://user-images.githubusercontent.com/52306002/90338946-9898f800-dfc3-11ea-9d94-cc104dc443e4.png)

- Criar outro model do 0 e reiniciar o processo. Mesmo problema.

- Excluir todos os models existentes e criar um único novo model. Mesmo problema.

- Excluir todas as assets do projeto e, apóis isso, excluir todos os models existentes e então criar um novo model do 0. Mesmo problema.

**Comment by danielramosbh74** [comment]
Olá Germain, passei exatamente pelo mesmo problema, assim como várias outras pessoas relataram lá no Discord, então vou te dizer algumas ações que fiz para resolvê-lo:

1. Excluí não apenas o Model, mas praticamente comecei "o projeto" do zero escolhendo tudo na localidade Dallas
2. Algumas vezes que teclei F5 para atualizar obtive a mensagem de erro 502 (bad gateway), então percebi nitidamente que não tinha muito o que fazer, pois era instabilidade e lentidão do servidor mesmo. Teclava F5 alguns segundos depois e, às vezes, melhorava a conexão. Mas chegou uma hora ontem a noite que eu já estava esgotado, então respeitei os meus limites, fui dormir e, hoje pela manhã, por volta de 8:00 hs, tentei de novo e... "pimba!" funcionou de primeira, pois muito provavelmente poucas pessoas estavam acessando o servidor neste horário.

OBS: 
1. Parabéns pela excelente explicação do seu problema, você foi extremamente detalhista e organizado. Fiz isso meio "na raça" via Discord... mas felizmente percebi que o problema não era só comigo, então esfriei a cabeça e deixei para tentar de novo hoje de manhã, o que felizmente funcionou.
2. Muita gente disse para trocar de localidade (ex. Tokyo, Seoul, etc), mas no novo canal "Dicas" está dizendo para permanecer no Dallas e eu consegui submeter minha app por lá.

https://desafio-ibm.mybluemix.net/

**Comment by GermainGirndt** [comment]
Muito obrigado pelo comentário completo, Daniel.

Como estou dormindo menos do que deveria, tive até medo de me perder olhando as discussões infinitas no Discord. Mas acho que posso abrir uma exceção na próxima vez hahaha.

-------

Por agora vou fechar a issue e tentar solucionar o problema conforme as suas instruções. Se o problema persistir, reabro.
