### ISSUE TITLE
Imagem em meio ao projeto meio peculiar....

### ISSUE THREAD

**Issue by GiovanaNp1** [maratonadev-br/desafio-1-2020#7]
Olá, estava mexendo no projeto da maratona e resolvi ver a estrutura do codigo, e percebi que tinha uma fota de uma margarina qualy no meio do projeto, isso está correto? É um easter egg da maratona???

![image](https://user-images.githubusercontent.com/34607779/90323239-f7636080-df34-11ea-86ab-a8b635f624ab.png)

**Comment by danitrod** [comment]
Oi Giovana, sim, você encontrou um easter egg. Na verdade essa imagem foi utilizada em um desafio do ano passado. 😄
